export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import './globals.css';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-[100vh] w-full p-0 m-0">{children}</body>
    </html>
  );
}
